# insert sample data was generated by AI. this was cleared as an acceptable use of AI prior to beginning this assessment.

USE libraryinventory;

INSERT INTO members (full_name, email) VALUES
	('James Reid', 'james.reid@email.com'),
	('Sarah Connor', 'sarah.connor@email.com'),
	('Liam Mackenzie', 'liam.mackenzie@email.com'),
	('Priya Patel', 'priya.patel@email.com');

INSERT INTO books (title, author, is_available) VALUES
	('The Pragmatic Programmer', 'David Thomas', FALSE),
	('Clean Code', 'Robert C. Martin', TRUE),
	('The Hobbit', 'J.R.R. Tolkien', FALSE),
	('1984', 'George Orwell', TRUE),
	('Dune', 'Frank Herbert', TRUE),
	('Norwegian Wood', 'Haruki Murakami', TRUE);

INSERT INTO loans (book_id, member_id, loan_date) VALUES
	(1, 2, '2025-04-15'),
	(3, 4, '2025-04-20');